const defaultConfigData = [
    {
        name: 'port',
        value: 9981
    }, {
        name: 'username',
        value: ''
    }, {
        name: 'password',
        value: ''
    }, {
        name: 'protocol',
        value: 'http'
    }, {
        name: 'hostname',
        value: ''
    }, {
        name: 'refresh',
        value: 5
    }, {
        name: 'ip_allowed',
        value: ''
    }, {
        name: 'telegram_bot_token',
        value: ''
    }, {
        name: 'telegram_id',
        value: ''
    }, {
        name: 'telegram_notification',
        value: false
    }, {
        name: 'telegram_notification_start_playback',
        value: false
    }, {
        name: 'telegram_notification_start_playback_text'
    }, {
        name: 'telegram_notification_stop_playback',
        value: false
    }, {
        name: 'telegram_notification_stop_playback_text'
    }, {
        name: 'telegram_notification_start_recording',
        value: false
    }, {
        name: 'telegram_notification_start_recording_text'
    }, {
        name: 'telegram_notification_stop_recording',
        value: false
    }, {
        name: 'telegram_notification_stop_recording_text'
    }, {
        name: 'telegram_notification_time',
        value: false
    }, {
        name: 'telegram_notification_time_text',
        value: ''
    }, {
        name: 'telegram_time_limit',
        value: ''
    }, {
        name: 'telegram_notification_ip_not_allowed',
        value: false
    }, {
        name: 'telegram_notification_ip_not_allowed_text',
        value: ''
    }
];

module.exports = defaultConfigData;