name: ci

on:
  push:
    branches:
      - main
      - dev
      - staging
  release:
    types:
      - released

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Determine Docker Tag
        id: tag
        run: |
          if [ "$GITHUB_REF" = "refs/heads/main" ]; then
            echo "latest"
          elif [ "$GITHUB_REF" = "refs/heads/dev" ]; then
            echo "dev"
          elif [ "$GITHUB_REF" = "refs/heads/staging" ]; then
            echo "staging"
          elif [ "$GITHUB_EVENT_NAME" = "release" ]; then
            echo "${{ github.event.release.tag_name }}"
          else
            echo "unknown"
          fi
        shell: bash
      -
        name: Build and push
        run: |
          docker build -t "${{ secrets.DOCKERHUB_USERNAME }}/tvspy:${{ steps.tag.outputs.stdout }}" .
          docker push "${{ secrets.DOCKERHUB_USERNAME }}/tvspy:${{ steps.tag.outputs.stdout }}"
